# configuring languages
# ex. force linking in front matter of the page: translationKey: (about-über uns- sobre nosotros)
de:
  baseURL: localhost/de
  languageName: Deutsch
  weight: 10
  contentDir: content/de
en:
  baseURL: localhost/en
  languageName: English
  weight: 20
  contentDir: content/en
