baseURL: http://localhost/
# disable taxonomy pages (defaults)
disableKinds:
- taxonomy
- taxonomyTerm
defaultContentLanguage: de
defaultContentLanguageInSubdir: true
languageCode: de-at
HUGO_DISABLELANGUAGES: en
title: proMusica
# alternate copyright company text
copyright: proMusica
# controls number of pages displayed on list pages
paginate: 2
# controls ths summary length on list pages
summaryLength: 7

# this is required to enable render of HTML in Markdown: true, false to desable
markup:
  goldmark:
    renderer:
      unsafe: true
# configuring languages
# ex. force linking in front matter of the page: translationKey: (about-über uns- sobre nosotros)
languages:
  de:
    baseURL: localhost
    languageName: Deutsch
    weight: 10
    contentDir: content/de
    menu:
     main:
     - name: Github
       url: http://www.github.com
       weight: 40
       params:
        blank: true
     - name: Google
       url: http://www.google.com
       weight: 50
       params:
        blank: true
  en:
    languageName: English
    weight: 20
    contentDir: content/en
    baseURL: localhost

    # menu links via config file
    menu:
      main:
      - name: Github
        url: http://www.github.com
        weight: 90
        params:
          blank: true
      - name: Google
        url: http://www.google.com
        weight: 100
        params:
          blank: true


